name: Check for discussion sections.

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-section:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: check discussion sections
      continue-on-error: true
      run: |
        warningFound=false
        for dir in content/*/; do
          found=false
          for file in "$dir"/*; do
            if grep -qiE 'discussion|questions|q&a|quiz' "$file" >/dev/null 2>&1; then
              found=true
              break
            fi
          done
          if [ "$found" == "true" ]; then
            echo "$dir: relevant section found"
          else
            echo "$dir: sections not found"
            warningFound=true
          fi
        done
        if [ "$warningFound" == "true" ]; then 
          echo "::warning::Some content directories did not contain any files with a discussion\questions\q&a section."
          echo "warning_found=true" >> $GITHUB_ENV
        else
          echo "warning_found=false" >> $GITHUB_ENV
        fi
    - name: Fail PR if section not found
      if: env.warning_found == 'true'
      run: |
        echo "Required sections not found."
        exit 1
