name: Check for discussion sections.

on:
  push:
    branches:
      - '**'

jobs:
  check-section:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: check discussion sections
      continue-on-error: true
      run: |
        for dir in content/*/; do
          found=false
          for file in "$dir"/*; do
            if grep -qiE 'discussion|questions|q&a|quiz' "$file" >/dev/null 2>&1; then
              found=true
              break
            fi
          done
          if [ "$found" == "true" ]; then
            echo "$dir: relevant section found"
          else
            echo "$dir: sections not found"
            warningFound=true
          fi
       done
       if [ "$warningFound" == "true" ]; then
          echo "::warning file=workflow::Warning: Some content directories did not contain any files with a discussion/questions/q&a section."
       fi
